"""add user_id to tasks

Revision ID: 67d300219a3e
Revises: 
Create Date: 2026-04-06 10:02:22.782512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d300219a3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'mobile')
    op.add_column('user_tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_tasks', 'user_table', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.drop_column('user_tasks', 'user_id')
    op.add_column('user_table', sa.Column('mobile', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
